### ISSUE TITLE
Practice Nested Repeaters

### ISSUE THREAD

**Issue by FilipeFernandes17** [FilipeFernandes17/2019-Sep-In-Class-DMIT-2018-A02#1]
Create a page that shows our suppliers and the products they offer. I will need to see info in the following "structure"

- **Supplier:**
  - Company Name:
  - Contact Name:
  - Phone Number:
  - **Product Summary:**
    - Product Name:
    - Category Name:
    - Unit Price:
    - Quantity/Unit:

##Tasks
- [x] Create LINQ query LinqPad
- [ ] Create classes for the *Read Model*
- [ ] Copy/Adapt LinqPad query to BLL method
- [ ] Create page with nested repeater
